import = [
  "~/.config/alacritty/themes/everforest_dark_medium.yml"
]

live_config_reload = true

[env]
TERM = "xterm-256color"

[window]
padding.x = 5

decorations = "Buttonless"

opacity = 0.9
blur = true

option_as_alt = "Both"

[font]
normal.family = "MesloLGS Nerd Font Mono"
size = 12
